import { useMemo, useRef, useState } from 'react';
import * as XLSX from 'xlsx';
import { createRoot } from 'react-dom/client';
import { AlertTriangle, BellRing, CalendarDays, ChevronDown, Clock3, Download, FileUp, LayoutDashboard, MapPin, Menu, Plus, Settings, ShieldCheck, Users, X } from 'lucide-react';
import './styles.css';
import './period.css';

type View = 'Visão geral' | 'Escalas' | 'Sobreaviso' | 'Colaboradores' | 'Inconsistências' | 'Configurações';
const team = [
  ['AM','Amanda Martins','Técnica de campo','Fortaleza, CE','12x36','Hoje, 07:00–19:00','ok'],
  ['BL','Bruno Lima','Técnico de campo','Fortaleza, CE','12x36','Hoje, 19:00–07:00','alert'],
  ['CS','Camila Souza','Supervisora','Maracanaú, CE','Seg–Sex','Hoje, 08:00–17:48','ok'],
  ['DR','Diego Ramos','Técnico de campo','Caucaia, CE','5x2','Em sobreaviso','standby'],
];
const nav: {label:View; icon:any}[] = [
  {label:'Visão geral',icon:LayoutDashboard},{label:'Escalas',icon:CalendarDays},{label:'Sobreaviso',icon:BellRing},{label:'Colaboradores',icon:Users},{label:'Inconsistências',icon:AlertTriangle},{label:'Configurações',icon:Settings},
];
function App(){
 const [view,setView]=useState<View>('Visão geral'); const [modal,setModal]=useState(false); const [menu,setMenu]=useState(false); const [toast,setToast]=useState(''); const [teamRows,setTeamRows]=useState(team); const [editing,setEditing]=useState<any>(null); const fileRef=useRef<HTMLInputElement>(null);
 const display = useMemo(()=>view==='Visão geral' ? 'Operação sob controle' : view, [view]);
 const act=(message:string)=>{setToast(message); setTimeout(()=>setToast(''),2600)};
 const importBase=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;try{const workbook=XLSX.read(await file.arrayBuffer(),{type:'array'});const sheet=workbook.Sheets['SOBREAVISO']||workbook.Sheets[workbook.SheetNames[0]];const rows=XLSX.utils.sheet_to_json<any[]>(sheet,{header:1,range:2,defval:''});const imported=rows.filter(r=>r[0]).map(r=>[String(r[0]).split(' ').map((n:string)=>n[0]).join('').slice(0,2).toUpperCase(),r[0],r[1]||'Colaborador',`${r[4]||'Não informado'}, ${r[3]||'--'}`,r[2]||'Não definida','A definir','ok',r[5]||'',r[6]||'']);setTeamRows(imported);act(`${imported.length} colaboradores importados da base.`)}catch{act('Não foi possível ler a planilha. Use o padrão de colunas informado.')}finally{e.target.value=''}};
 const saveEdit=()=>{setTeamRows(rows=>rows.map(r=>r[1]===editing.original?[editing.initial,editing.name,editing.role,`${editing.locality}, ${editing.uf}`,editing.team,editing.status,'ok',editing.ga,editing.go]:r));setEditing(null);act('Cadastro do colaborador atualizado.')};
 return <div className="app">
  <aside className={menu?'sidebar mobile-open':'sidebar'}><div className="brand"><div className="logo">S</div><div><strong>Sobreaviso</strong><span>Gestão de escalas</span></div><button className="close" onClick={()=>setMenu(false)}><X/></button></div>
   <div className="workspace"><span>AM</span><div><b>Alvorada Manutenção</b><small>Ambiente de produção</small></div><ChevronDown size={16}/></div>
   <nav>{nav.map(({label,icon:Icon})=><button key={label} className={view===label?'active':''} onClick={()=>{setView(label);setMenu(false)}}><Icon size={19}/>{label}{label==='Inconsistências'&&<em>3</em>}</button>)}</nav>
   <div className="side-bottom"><button onClick={()=>act('Central de ajuda aberta')}><ShieldCheck size={19}/>Ajuda e suporte</button><div className="profile"><span>WM</span><div><b>Wanderson M.</b><small>Administrador</small></div><ChevronDown size={15}/></div></div>
  </aside>
  <main><header><button className="hamb" onClick={()=>setMenu(true)}><Menu/></button><div><p>Domingo, 16 de agosto de 2026</p><h1>{display}</h1></div><div className="header-actions"><input ref={fileRef} className="file-input" type="file" accept=".xlsx,.xls" onChange={importBase}/><button className="export" onClick={()=>fileRef.current?.click()}><FileUp size={18}/>Importar base</button><button className="icon-btn" onClick={()=>act('Você não tem novas notificações')}><BellRing size={20}/><i/></button><button className="export" onClick={()=>act('A exportação Excel foi preparada')}><Download size={18}/>Exportar</button><button className="primary" onClick={()=>setModal(true)}><Plus size={18}/>Nova escala</button></div></header>
  <section className="period"><div className="period-icon"><CalendarDays size={20}/></div><div><span>Ciclo de apuração vigente</span><b>15 de agosto de 2026 — 14 de setembro de 2026</b><small>Os períodos são iniciados automaticamente no dia 15 e encerrados no dia 14 do mês seguinte.</small></div><button className="outline period-button" onClick={()=>act('O ciclo de apuração está configurado como 15 a 14.')}>15 → 14 <Settings size={15}/></button></section>
  <section className="notice"><div className="notice-icon"><AlertTriangle size={20}/></div><div><b>3 pontos precisam da sua atenção</b><p>Há jornadas com intervalo incompleto ou conflitos de sobreaviso nesta semana.</p></div><button onClick={()=>setView('Inconsistências')}>Ver inconsistências</button></section>
  <section className="metrics"><Metric title="Colaboradores ativos" value="48" hint="2 afastados hoje" icon={Users} color="blue"/><Metric title="Em sobreaviso" value="8" hint="Próxima troca às 19:00" icon={BellRing} color="purple"/><Metric title="Horas previstas" value="1.764h" hint="Ciclo: 15 ago. a 14 set." icon={Clock3} color="green"/><Metric title="Horas de sobreaviso" value="312h" hint="Ciclo: 15 ago. a 14 set." icon={CalendarDays} color="orange"/></section>
  <section className="content-grid"><div className="card schedule"><div className="card-head"><div><h2>Escala de hoje</h2><p>Acompanhamento das equipes em campo · clique em um colaborador para editar</p></div><button className="link" onClick={()=>setView('Escalas')}>Ver escala completa</button></div><div className="date-row"><button>‹</button><div><b>16</b><span>DOM</span></div><div><b>17</b><span>SEG</span></div><div><b>18</b><span>TER</span></div><div><b>19</b><span>QUA</span></div><div><b>20</b><span>QUI</span></div><div><b>21</b><span>SEX</span></div><div><b>22</b><span>SÁB</span></div><button>›</button></div><div className="table-head"><span>COLABORADOR</span><span>ESCALA</span><span>JORNADA / STATUS</span></div>{teamRows.slice(0,6).map(([initial,name,role,place,scale,status,state,ga='',go=''])=><div className="person editable" key={name} role="button" tabIndex={0} onClick={()=>{const parts=String(place).split(', ');setEditing({original:name,initial,name,role,locality:parts[0],uf:parts[1]||'',team:scale,status,ga,go})}}><span className={'avatar '+state}>{initial}</span><div className="identity"><b>{name}</b><small>{role} · {place}</small></div><span className="pill">{scale}</span><div><b className={state==='alert'?'warning':state==='standby'?'violet':''}>{status}</b>{state==='alert'&&<small className="warning">Intervalo a revisar</small>}</div></div>)}</div>
  <div className="right-col"><div className="card"><div className="card-head"><div><h2>Sobreaviso</h2><p>Plantão vigente</p></div><button className="dots">•••</button></div><div className="standby"><div className="status-dot"/><div><b>Equipe Norte está de plantão</b><p>Dom, 07:00 — Seg, 07:00</p></div></div><div className="pair"><span className="avatar standby">DR</span><span className="avatar ok">AM</span><div><b>Diego e Amanda</b><small>Dupla técnica · Fortaleza</small></div></div><button className="outline" onClick={()=>setView('Sobreaviso')}>Gerenciar sobreaviso</button></div>
   <div className="card holidays"><div className="card-head"><div><h2>Próximos eventos</h2><p>Feriados e afastamentos</p></div><button className="link">Calendário</button></div><div className="event"><div><b>07</b><span>SET</span></div><p><b>Independência do Brasil</b><small>Feriado nacional</small></p></div><div className="event"><div className="purple-bg"><b>15</b><span>OUT</span></div><p><b>Férias — Camila Souza</b><small>15 a 29 de outubro</small></p></div></div></div></section>
  <section className="bottom-cards"><div className="card chart"><div><h2>Horas planejadas × realizadas</h2><p>Agosto de 2026 · em horas</p></div><div className="bars">{[48,63,57,76,68,86,74,92,78,88,61,82].map((h,i)=><span key={i} style={{height:h+'%'}}/> )}</div><div className="legend"><i/>Planejadas <i className="actual"/>Realizadas</div></div><div className="card issues"><div className="card-head"><div><h2>Inconsistências recentes</h2><p>Revisão necessária</p></div><button className="link" onClick={()=>setView('Inconsistências')}>Ver todas</button></div><div className="issue"><span className="issue-icon">!</span><p><b>Descanso entre jornadas</b><small>Bruno Lima · 17 de ago.</small></p><button onClick={()=>act('Inconsistência aberta para revisão')}>Revisar</button></div><div className="issue"><span className="issue-icon">!</span><p><b>Conflito de sobreaviso</b><small>Equipe Sul · 18 de ago.</small></p><button onClick={()=>act('Inconsistência aberta para revisão')}>Revisar</button></div></div></section>
  </main>
  {modal&&<div className="overlay"><div className="modal"><button className="modal-x" onClick={()=>setModal(false)}><X/></button><span className="modal-icon"><CalendarDays/></span><h2>Criar nova escala</h2><p>Defina a jornada, os técnicos e a localidade.</p><label>Modelo de escala<select><option>12x36 — Diurna</option><option>5x2 — Administrativo</option><option>6x1 — Operacional</option></select></label><label>Localidade<select><option>Fortaleza, CE</option><option>Maracanaú, CE</option><option>Caucaia, CE</option></select></label><div className="modal-actions"><button className="outline" onClick={()=>setModal(false)}>Cancelar</button><button className="primary" onClick={()=>{setModal(false);act('Escala criada com sucesso')}}>Criar escala</button></div></div></div>}
  {editing&&<div className="overlay"><div className="modal"><button className="modal-x" onClick={()=>setEditing(null)}><X/></button><span className="modal-icon"><Users/></span><h2>Editar colaborador</h2><p>Atualize os dados do cadastro e sua estrutura de gestão.</p><label>Nome<input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label>Função<input value={editing.role} onChange={e=>setEditing({...editing,role:e.target.value})}/></label><div className="form-row"><label>UF<input value={editing.uf} onChange={e=>setEditing({...editing,uf:e.target.value.toUpperCase()})}/></label><label>Localidade<input value={editing.locality} onChange={e=>setEditing({...editing,locality:e.target.value})}/></label></div><label>Equipe<input value={editing.team} onChange={e=>setEditing({...editing,team:e.target.value})}/></label><label>Gestor Administrativo (G.A)<input value={editing.ga} onChange={e=>setEditing({...editing,ga:e.target.value})}/></label><label>Gestor Operacional (G.O)<input value={editing.go} onChange={e=>setEditing({...editing,go:e.target.value})}/></label><div className="modal-actions"><button className="outline" onClick={()=>setEditing(null)}>Cancelar</button><button className="primary" onClick={saveEdit}>Salvar alterações</button></div></div></div>}
  {toast&&<div className="toast">{toast}</div>}
 </div>
}
function Metric({title,value,hint,icon:Icon,color}:{title:string,value:string,hint:string,icon:any,color:string}){return <div className="metric card"><div className={'metric-icon '+color}><Icon size={21}/></div><p>{title}</p><h2>{value}</h2><small>{hint}</small></div>}
createRoot(document.getElementById('root')!).render(<App/>);
